version: "1.0"
config:
  - stage: boot
    tasks:
      - task: extendRootPartition
  
  - stage: preReady
    tasks:
      - task: activateWindows
        inputs:
          activation:
            type: amazon
      
      - task: setDnsSuffix
        inputs:
          suffixes:
            - $REGION.ec2-utilities.amazonaws.com
      
      - task: setAdminAccount
        inputs:
          password:
            type: random
      
      - task: setWallpaper
        inputs:
          path: C:\Windows\Web\Wallpaper\Windows\img0.jpg
  
  - stage: postReady
    tasks:
      - task: startSsm

# Made with Bob
